behaviors:
  PlayGame:  
    trainer_type: sac
    hyperparameters:
      batch_size: 256
      buffer_size: 500000
      learning_rate: 0.0003
      init_entcoef: 0.05 
      reward_signal_steps_per_update: 1500
      steps_per_update: 1.0  
      tau: 0.005  
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true